### PR TITLE
Sort iVar consensus FASTA by sample name

### PR DESCRIPTION
**Pull request by fanninpm**
This also affects downstream processes. I need to test this on a larger sample of data before I can confidently merge this.

Addresses https://github.com/usafsam/mad_river_wf/pull/12#discussion_r815262737

### CODE REVIEW

**Review by friesac — COMMENTED** [review]
I'm honestly not familiar with the function and can't really see how it works on a fasta file... given that a fasta format is ">name1\nAACCTT\n>name2\nAACCTA". You are sorting the file as though each specimen is two lines in the consensus fasta? I can think of some simple R code to rearrange and then feed into nextclade and pangolin.

**Comment by fanninpm** [comment]
The [`collectFile()`](https://nextflow.io/docs/latest/operator.html#collectfile) operator acts on a _channel_. Here, the channel has individual FASTA files of one sequence each. My idea is to `sort` the FASTA files in lexicographical order based on file name before they go into the FASTA, which `sort: true` apparently wasn't doing.

**Review by friesac — APPROVED** [review]

**Comment by fanninpm** [comment]
I still need to test it on a computer with enough cores to make the parallelism scramble the order in which things finish, and I will do that tomorrow.

**Comment by fanninpm** [comment]
Test results:

- This sorted the combined consensus FASTA. However, Pangolin and Nextclade did their own shuffling (while VADR seems to be unaffected).
  - For Nextclade, [we simply need to pass the `--in-order` flag](https://docs.nextstrain.org/projects/nextclade/en/latest/changes/CHANGELOG.html?highlight=in-order#nextclade-cli-v1). I'll add this to the PR tonight.
  - For Pangolin, the sequences that failed QC are segregated from those that passed QC. [Here's the code in Pangolin responsible for joining different groups together.](https://github.com/cov-lineages/pangolin/blob/26fdaf68dfbe8761cc9f2fe51af5a125730a4351/pangolin/scripts/pangolearn.smk#L114-L165)

**Review by friesac — APPROVED** [review]
Right, I forgot pangolin does that instead of by input order. All these look fine to me.

**Pull request merged**
